### ISSUE TITLE
Remove include for chart.js from header

### ISSUE THREAD

**Issue by lukas-dachtler** [IT4Kids/website#15]
**chart.js** shouldn't be loaded in the header for all sites. Instead the script should only be included in the status pages.

https://github.com/IT4Kids/website/blob/8af6b4bfb977d15654f5ff58b6165f802b860dd7/layouts/partials/header.html#L39

**Comment by FynnMazurkiewicz** [comment]
Closed by b39d3f76ae73dd1ebd150a86c9d2f68699ca79c2.
